### ISSUE TITLE
Dev install instructions miss setup_db before create_package

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches-docs#231]
#### describe the issue
https://arches.readthedocs.io/en/stable/creating-a-development-environment/ says to run create_package as step 6, immediately after creating the project.

This fails, as setup_db hasn't been run and thus the database doesn't exist in postgres/elastic.

Fix is obvious... run setup_db :)

##### please add links to existing docs or code (if relevant)

```
(ENV) rs2668@ip-10-5-39-114:~/Development/projects/entities$ python ./manage.py packages -o create_package -d ../../packages/entities
No module named 'arches.settings_local'
Error attempting to load settings from relative '.settings_local'. Attempting 'arches.settings_local' import
Error attempting to load settings from 'arches.settings_local.py'.
No module named 'arches.settings_local'
operation: create_package
Creating template package in ../../packages/entities
added ../../packages/entities/business_data/files/.gitkeep
added ../../packages/entities/business_data/relations/.gitkeep
added ../../packages/entities/business_data/resource_views/.gitkeep
added ../../packages/entities/extensions/datatypes/.gitkeep
added ../../packages/entities/extensions/functions/.gitkeep
added ../../packages/entities/extensions/widgets/.gitkeep
added ../../packages/entities/extensions/css/.gitkeep
added ../../packages/entities/extensions/bindings/.gitkeep
added ../../packages/entities/extensions/card_components/.gitkeep
added ../../packages/entities/extensions/plugins/.gitkeep
added ../../packages/entities/graphs/branches/.gitkeep
added ../../packages/entities/graphs/resource_models/.gitkeep
added ../../packages/entities/ontologies/.gitkeep
added ../../packages/entities/map_layers/mapbox_spec_json/overlays/.gitkeep
added ../../packages/entities/map_layers/mapbox_spec_json/basemaps/.gitkeep
added ../../packages/entities/preliminary_sql/.gitkeep
added ../../packages/entities/reference_data/concepts/.gitkeep
added ../../packages/entities/reference_data/collections/.gitkeep
added ../../packages/entities/system_settings/.gitkeep
FATAL:  database "entities" does not exist

Could not read resource to resource constraints
Traceback (most recent call last):
  File "/home/rs2668/Development/ENV/lib/python3.8/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/home/rs2668/Development/ENV/lib/python3.8/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/rs2668/Development/ENV/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/rs2668/Development/ENV/lib/python3.8/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  database "entities" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/home/rs2668/Development/ENV/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/rs2668/Development/ENV/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/rs2668/Development/ENV/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/rs2668/Development/ENV/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/rs2668/Development/arches/arches/management/commands/packages.py", line 306, in handle
    self.create_package(options["dest_dir"])
  File "/home/rs2668/Development/arches/arches/management/commands/packages.py", line 466, in create_package
    self.export_resource_graphs(os.path.join(dest_dir, "graphs", "resource_models"), "true")
  File "/home/rs2668/Development/arches/arches/management/commands/packages.py", line 344, in export_resource_graphs
    resource_graphs = ResourceGraphExporter.get_graphs_for_export(["resource_models"])
  File "/home/rs2668/Development/arches/arches/app/utils/data_management/resource_graphs/exporter.py", line 85, in get_graphs_for_export
    resource_graph_query = JSONSerializer().serializeToPython(
  File "/home/rs2668/Development/arches/arches/app/utils/betterJSONSerializer.py", line 52, in serializeToPython
    return self.handle_object(obj, self.selected_fields, self.exclude)
  File "/home/rs2668/Development/arches/arches/app/utils/betterJSONSerializer.py", line 93, in handle_object
    for item in object:
  File "/home/rs2668/Development/ENV/lib/python3.8/site-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/home/rs2668/Development/ENV/lib/python3.8/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/rs2668/Development/ENV/lib/python3.8/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/rs2668/Development/ENV/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1138, in execute_sql
    cursor = self.connection.cursor()
  File "/home/rs2668/Development/ENV/lib/python3.8/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/home/rs2668/Development/ENV/lib/python3.8/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/home/rs2668/Development/ENV/lib/python3.8/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/home/rs2668/Development/ENV/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/rs2668/Development/ENV/lib/python3.8/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/home/rs2668/Development/ENV/lib/python3.8/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/rs2668/Development/ENV/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/rs2668/Development/ENV/lib/python3.8/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  database "entities" does not exist
```

**Comment by mradamcox** [comment]
Nice, thanks for this ticket. That section is slated for a makeover very soon. https://github.com/archesproject/arches-docs/issues/168

**Comment by mradamcox** [comment]
Addressed
